export enum EnvironmentEnums {
    TYPE = 'MYSQL_TYPE',
    HOST = 'MYSQL_HOST',
    PORT = 'MYSQL_PORT',
    USERNAME = 'MYSQL_USERNAME',
    PASSWORD = 'MYSQL_PASSWORD',
    DATABASE = 'MYSQL_DATABASE',
    MIGRATION_DIR = 'CLI_MIGRATION_DIRECTORY',
    NODE = 'MYSQL_NODE',
}
